### ISSUE TITLE
Help to connect

### ISSUE THREAD

**Issue by QBJack** [stich86/UF-Instant-Mod#12]
Hello folks,

I have read evrthing here forth and back but I still need help to connect to my UFInstant SFP with stock firmware.
I have a UDM SE with unifi OS 3.x. I tried different configurations but the only thing I've achieved is to get an open port 10001 on nmap scan. No SSH oder telnet is possible there - but could not try telnet from UDM as there is no telnet available.

Please help on that.

Thanks in advance.

Cheers,
Thomas

**Comment by stich86** [comment]
Hi @QBJack,

if your stick doesn't have telnet/ssh enable by default only way is to use UART console and enable from it
