### ISSUE TITLE
Any chance to get a copy of the 4.4.8 firmware?

### ISSUE THREAD

**Issue by d3vi1** [stich86/UF-Instant-Mod#14]
UI Firmware 4.4.8 finally has a public release. Any chance you could provide it?

Thanks,
R.

**Comment by stich86** [comment]
i'll try to extract in the next few days and upload on the git :)

**Comment by d3vi1** [comment]
Hi @stich86,

Can you provide us with a guide for extracting the FW updates? I would like to attempt to extract 4.4.8 and 4.4.9 in order to create a pull request.

Thanks,
R.

**Comment by stich86** [comment]
Hi, i've added the requested firmware.
To extract from original UF-OLT just download the tar file and the, using **sudo** and **binwalk** on a Linux machine, extract the file `squashfs.tmp`

After extracted, you will find all FW into path: `./squashfs-root/usr/share/onufw/`

Where is the 4.4.9? In the UF site I see only 4.4.8
