### ISSUE TITLE
UART

### ISSUE THREAD

**Issue by Pukkahq** [stich86/UF-Instant-Mod#3]
Silly questions, when I try and connect via the UART port. i am using an external power supply for 3.3v and a speed of 19200 8/n/1 but all i am seeing is random text. can i ask what setting are you using?

**Comment by stich86** [comment]
UART is at 115200 8n1 :)

**Comment by Pukkahq** [comment]
my screen looks like this. any pointers? I am using a cp210x
![image](https://user-images.githubusercontent.com/15746724/184416415-51e42db9-c638-49c9-b1f0-956c308054b8.png)

**Comment by stich86** [comment]
double check speed and connection.
You should attach also GND, not only TX\RX

**Comment by Pukkahq** [comment]
GND has fixed it :)

**Comment by stich86** [comment]
good, i close the issue ;)
