### ISSUE TITLE
netcat no available

### ISSUE THREAD

**Issue by hugomon** [stich86/UF-Instant-Mod#6]
Hi, any idea how I can fix this?

```
# nc
/bin/sh: nc: not found
```
The stick version is older than the one mentioned in the repo.

```
# nv getenv | grep sw_ver
sw_version0=v4.1.0.359-b87.191101.0940
sw_version1=v4.1.0.359-b87.191101.0940
```

**Comment by hugomon** [comment]
I can push the file via ssh from a linux machine  `scp rootfs_MOD_UFINST_220505 ubnt@192.168.1.1:/tmp/mtd7`
**Is it safe to do it if the version of sw is different?` v4.1.0.359-b87.191101.0940 vs v4.3.1.913-d48.210415.0811`**

**Comment by stich86** [comment]
yes on stock firmware you can use this trick
