### ISSUE TITLE
Blocked on fw 4.1.0

### ISSUE THREAD

**Issue by davicom88** [stich86/UF-Instant-Mod#7]
Hi, could you please give me some advice.

I cant do 'nc' command on ufiber telnet session

I cant connect via ssh ut just telnet 

And I dont know i can upgrade fw, i see there is a command 'fwupdate' but need a 'bin' for firmware, this i don't know where get and most importantly how can i put into ufiber (scp obviously doesnt work without ssh)

Could you give me some tips?

Thanks

**Comment by davicom88** [comment]
Update. I enabled ssh, so i assume i will be able to upload via scp the files needed to update the firmware. Could you please explain which file do I need flash on m6/k1 at this point?

**Comment by stich86** [comment]
Hi @davicom88,

you should copy this file https://github.com/stich86/UF-Instant-Mod/blob/main/Original%20Firmwares/v4.4.2.1248-550.220304.1317/UF-ONU.UF-INSTANT.v4.4.2.1248-550.220304.1317.img on the stick and then run the update of firmware with  command:

`/bin/fwupdate path/UF-ONU.UF-INSTANT.v4.4.2.1248-550.220304.1317.img`

Then after reboot check which partition is currenctly active with the command

`nv getenv sw_active`

if it's `0` you should flash `k1` (standby firmware), otherwise `k0`

Plese refer to the README.md for custom root flashing :)

**Comment by davicom88** [comment]
Hi, infinite thanks for your support. I will try after work and I let you know.

**Comment by davicom88** [comment]
Hi @stich86 
so every flash and modding procedure was successful, unfortunately I can't get it aligned: with the same data used on the zyxel this doesn't align, or maybe I'm wrong something, do you have any suggestions? The router keeps giving this error from the log, which is the ploam password that the zyxel did not ask ???:
```
Sep 1 14:10:58 ER12 pppd [6495]: Timeout waiting for PADO packets
Sep 1 14:11:01 ER12 pppd [6871]: Timeout waiting for PADO packets
Sep 1 14:12:14 ER12 pppd [6495]: Timeout waiting for PADO packets
Sep 1 14:12:16 ER12 pppd [6871]: Timeout waiting for PADO packets
Sep 1 14:13:29 ER12 pppd [6495]: Timeout waiting for PADO packets
Sep 1 14:13:31 ER12 pppd [6871]: Timeout waiting for PADO packets
Sep 1 14:14:44 ER12 pppd [6495]: Timeout waiting for PADO packets
Sep 1 14:14:46 ER12 pppd [6871]: Timeout waiting for PADO packets
Sep 1 14:15:17 ER12 kernel: Failed to read SFP EEPROM_0 at byte 45 val -6 !!
Sep 1 14:15:17 ER12 kernel: Failed to read SFP EEPROM_1 at byte 0 val -6 !!
Sep 1 14:15:33 ER12 kernel: eth11: 1000 Mbps Full duplex, port 0
Sep 1 14:15:59 ER12 pppd [6495]: Timeout waiting for PADO packets
Sep 1 14:16:01 ER12 pppd [6871]: Timeout waiting for PADO packets
```
Data entered:
` # flash set GPON_ONU_MODEL V6.0` (also tried F601VDF) 'equipment id on zyxel'
`# flash set CUSTOM_OMCI_SW_VER1 V6.0.10N40`
CUSTOM_OMCI_SW_VER1 = V6.0.10N40 'sw version on zyxel'
 `# flash set GPON_SN ztegce ********`
GPON_SN = ztegce *********
`# flash set PON_VENDOR_ID zteg`
PON_VENDOR_ID = zteg
`# flash set OMCI_FAKE_OK 1`
OMCI_FAKE_OK = 1
`# flash set OMCI_OLT_MODE 1`

**Comment by stich86** [comment]
Are you Italian?
Looking at your information it's a ZTE F6005 used here for 2.5G FTTH line

Let me know, we have a telegram group that can help you to connect on your OLT

**Comment by davicom88** [comment]
hello yes I'm Italian, honestly for the moment I gave up, from the logs as I told you the router failed to read a part of the eeprom, furthermore as soon as I connected the fiber the uf instant module kept restarting in a continuous loop, I don't even know if I can re-enter it. at the moment I put back the external ont which is a zte 601. if you have any suggestions please tell me maybe in my spare time I try to re-enter it and do the configuration from scratch starting from the default one. however it would be very useful to really know what are the only data needed without touching anything else, on the zyxel stick they were: equip_id, software_vers, serial_id, vendor_id

**Comment by fiberexplorer** [comment]
> Update. I enabled ssh, so i assume i will be able to upload via scp the files needed to update the firmware. Could you please explain which file do I need flash on m6/k1 at this point?

Hi! could you clarify how you enabled the SSH access? I'm trying with no results?
Many Tks
