### ISSUE TITLE
Problem with your procedure for Custom rootFS

### ISSUE THREAD

**Issue by jcamiade** [stich86/UF-Instant-Mod#8]
Hi,

On this part of your procedure, i don't understand how to ...........
------------------
on the telnet\ssh session on UF-INSTANT, go to cd /tmp
run this command: nc -l -p 1234 > mtd7 (if you are on image1, use mtd5 as name)
--> I don't have nc on the UF Instant even with the last firmware update official 4.4.2

on your computer, go where the custom root fs is downloaded rootfs_MOD_UFINST_220505 (you can found it under folder Modified RootFS - md5 4ae50a56f5c4768ea5ac95d4298a01ba)
run this command: nc 192.168.1.1 1234 < rootfs_MOD_UFINST_220505
when done, on the telnet\ssh session your nc command has exited, you have a file called mtd7 (or mtd5), run an md5sum on that file and compare the md5 with the original one, ONLY IF these are equal proceed with the next step

--------------------

Also, Even if i want to change of sw0 or sw1 , after reboot , the same version boot.

Could you help me ?

Thanks

**Comment by stich86** [comment]
hi @jcamiade,

what you don't understand? Let me know

**Comment by jcamiade** [comment]
Thanks for your answer.

I update my ubiquiti Instant on the last version 4.4.2 but i don't know how to put / inject your custom FS on it.

Thanks

**Comment by stich86** [comment]
you should connect over ssh or telnet on the stick, put nc (netcat) on listening the stick (with the command provided `nc -l -p 1234 > mtdX`), then use same nc client (if on windows machine, you can download from [here ](https://joncraton.org/blog/46/netcat-for-windows/) to push the file (with the commando provided `nc 192.168.1.1 1234 < rootfs_MOD_UFINST_220505`)
