### ISSUE TITLE
What was changed, exactly, on the modded rootfs?

### ISSUE THREAD

**Issue by guipoletto** [stich86/UF-Instant-Mod#9]
Hi, it is not clear (to me), what files exactly were changed in the modded rootfs

I'm interested in the vendor lock-in part, specifically (as i have control over the OLT)
Running the latest version of the firmware:
v4.4.3.1442-23c.220908.1227

**Comment by stich86** [comment]
the moddes rootfs is based on VSOL 2801F firmware, so there is nothing stock from UI :)
